services:
  db_mysql:
    image: mysql:8.0
    container_name: didacta_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DB_NAME:-didacta_db}
    volumes:
      - mysql_data_prod:/var/lib/mysql

  db_mongo:
    image: mongo:5.0
    container_name: didacta_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-rootpassword}
    volumes:
      - mongo_data_prod:/data/db

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: didacta_backend
    restart: always
    depends_on:
      - db_mysql
      - db_mongo
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
      - DB_HOST=db_mysql
      - DB_NAME=${DB_NAME:-didacta_db}
      - DB_USER=root
      - DB_PASSWORD=${DB_PASSWORD:-rootpassword}
      - MONGO_URI=mongodb://${MONGO_USER:-root}:${MONGO_PASSWORD:-rootpassword}@db_mongo:27017/
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1,didacta.com}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS:-http://localhost}
    expose:
      - "8001"

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: didacta_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  mysql_data_prod:
  mongo_data_prod:
